#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
上書きロジック不発の根本原因分析
"""

print('=' * 90)
print('🔴 上書きロジック不発の根本原因分析')
print('=' * 90)
print()

# 現在のロジック
rss_published = '2025-12-23T19:30:44'
api_scheduled = '2025-12-28T18:00:00Z'
api_published = '2025-12-23T19:30:44Z'

print('【 現在のロジックフロー 】')
print('-' * 90)
print()
print('1️⃣ RSS から取得')
print(f'   RSS published_at = {rss_published}')
print()

print('2️⃣ YouTube API プラグイン有効化時、以下を取得')
print(f'   API - scheduledStartTime = {api_scheduled} ⭐ 優先度最高')
print(f'   API - publishedAt = {api_published} (優先度3)')
print()

print('3️⃣ youtube_rss.py - save_to_db() のロジック')
print()
print('   api_published_at = None')
print('   if scheduledStartTime:')
print('       api_published_at = scheduledStartTime  ← 実行される！')
print('   elif actualStartTime:')
print('       ...')
print('   elif publishedAt:')
print('       api_published_at = publishedAt')
print()

print('❌ しかし実際には...')
print('   DB に登録された値 = RSS published_at')
print('   理由：insert_video() で既存動画を検出 → False を返す')
print()

print('4️⃣ 上書きロジック')
print()
print('   if api_published_at and api_published_at != video["published_at"]:')
print('       database.update_published_at(...)')
print()

print('⚠️ ここが致命的な問題！')
print(f'   実際に比較されている値：')
print(f'   api_published_at = {api_published}')
print(f'   （scheduledStartTime ではなく publishedAt に落ちている）')
print(f'   video["published_at"] = {rss_published}')
print()

api_clean = api_published.replace('Z', '')
rss_clean = rss_published

print('   値の比較：')
print(f'   "{api_clean}" != "{rss_clean}"')
print()

if api_clean == rss_clean:
    print('   → FALSE（同じ値）')
    print('   → update_published_at() が呼ばれない')
    print()
    print('   🚨 scheduledStartTime = 2025-12-28T18:00:00Z が完全に捨てられている！')

print()
print('=' * 90)
print('【 本来のあるべきロジック 】')
print('=' * 90)
print()
print('優先度ルール：')
print('  1. API - scheduledStartTime (配信予定時刻)')
print('  2. API - actualStartTime (実際配信開始時刻)')
print('  3. API - publishedAt (動画公開時刻)')
print('  4. RSS - published_at (RSS値)')
print()
print('初回登録時：')
print(f'  ✅ final_published_at = {api_scheduled}')
print()
print('既存動画の上書き：')
print(f'  if {api_scheduled} != {rss_published}:')
print(f'      update_published_at()')
print('      → 上書きされるべき')
print()

print('=' * 90)
print('【 バグの影響 】')
print('=' * 90)
print()
print('現在：')
print(f'  DB published_at = {rss_published}  ❌ 古い値')
print()
print('期待値：')
print(f'  DB published_at = {api_scheduled}  ✅ 配信予定時刻')
print()
print('Bluesky投稿時：')
print(f'  テンプレートに使われる日時 = {rss_published}')
print(f'  本来あるべき日時 = {api_scheduled}')
print()
print('結果：投稿に間違った配信日時が表示される')
print()

print('=' * 90)
print('【 根本原因 】')
print('=' * 90)
print()
print('❌ 現在のロジック：')
print('   1. RSS で検出 → insert_video(..., published_at=RSS値)')
print('   2. API から scheduledStartTime を取得')
print('   3. 上書きロジック: if api_published_at != video["published_at"]:')
print('   4. しかし API publishedAt == RSS published_at なので上書き不発')
print('   5. scheduledStartTime は捨てられる')
print()
print('✅ 修正案：')
print()
print('方案1（推奨）：RSS登録時に優先度を正しく適用')
print('   final_published_at を以下で決定：')
print('   1️⃣ API scheduledStartTime あれば使う')
print('   2️⃣ API actualStartTime あれば使う')
print('   3️⃣ API publishedAt あれば使う')
print('   4️⃣ RSS published_at を使う')
print()
print('方案2：上書きロジックを強化')
print('   API scheduledStartTime と DB published_at を直接比較')
print('   （API publishedAt との比較ではなく）')
print()
print('方案3：別テーブルに「正確な配信予定時刻」を保存')
print('   published_at（公開時刻）と')
print('   scheduled_start_time（配信予定時刻）を分離')
print()

print('=' * 90)
